blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/mayahq/maya-red-scheduler/discussions
    about: Please use the forum for asking questions and getting help, providing feedback and discussing new ideas and enhancements.
